### ISSUE TITLE
Can you please give an example of how to use it. I tried it but failed to working RTL mode. But it works in LTR mode.

### ISSUE THREAD

**Issue by mostasim** [duolingo/rtl-viewpager#12]
### Required Information

- RtlViewPager Version: 1.0.3
- Android Version and Device (Marshmallow, Walton NH Lite):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by m7mdyahia** [comment]
it works according to the locale of the app
so either change the locale of device from settings or change the app locale

**Comment by mibrahimdev** [comment]
@m7mdyahia what if I need it for just one screen and other screens in english?

**Comment by DavidDTA** [comment]
Use the [`android:layoutDirection`](https://developer.android.com/reference/android/view/View.html#attr_android:layoutDirection) xml property.

**Comment by mibrahimdev** [comment]
@DavidDTA thanks, but I figured the issue, before anything I was supposed to add "supportRTl" in the manifest
