### ISSUE TITLE
SavedState is not preserved.

### ISSUE THREAD

**Issue by MkazemAkhgary** [duolingo/rtl-viewpager#15]
Saved state works correctly when we set adapter again, but in your `setAdapter`, viewpager is re-positioned to 0 defeating the whole purpose of saving state.

```java
    @Override
    public void setAdapter(PagerAdapter adapter) {
        if (adapter != null) {
            adapter = new ReversingAdapter(adapter);
        }
        super.setAdapter(adapter);
        setCurrentItem(0); // this line defeats saved state purpose.
    }
```

**Solution:**

if `setCurrentItem()` is required for some initialization, do `setCurrentItem(getCurrentItem())` or simply remove this line so viewpager selected page is always preserved when restoring saved state.

**Comment by DavidDTA** [comment]
Thank you for your submission.  The reason that line was added is so that the `ViewPager` will start at the rightmost view in RTL mode.  `setCurrentItem(getCurrentItem())` does not have the desired effect since both methods perform the same reversing behaviors.  I think a correct solution might look similar to the code used for restoring the position in `ViewPager` (see `mRestoredCurItem`).

I will not be able to get to fixing this issue in the near future, but will absolutely help facilitate a pull request.

**Comment by MkazemAkhgary** [comment]
I was able to fix this problem using an additional boolean to determine if adapter is ever set.
In RtlPropertiesChanged, current item is updated. note that you should also include this boolean in saved state.

```java
    private int layoutDirection = ViewCompat.LAYOUT_DIRECTION_LTR;
    private boolean adapterWasSet = false;

    public final int getAdapterCount() {
        return super.getAdapter() != null ? super.getAdapter().getCount() : 0;
    }

    /**
     * returns reversed position in RTL layout direction.
     */
    private int getActual(int position) {
        return isRtl() ? getAdapterCount() - position - 1 : position;
    }

    public void onRtlPropertiesChanged(int layoutDirection) {
        PagerAdapter adapter = super.getAdapter();
        if (adapter != null && this.layoutDirection != layoutDirection) {
            this.layoutDirection = layoutDirection;
            adapter.notifyDataSetChanged();
            super.setCurrentItem(adapter.getCount() - super.getCurrentItem() - 1); // adapter is reversed. current position must change as well
        }
    }

    @Override
    public void setAdapter(@Nullable PagerAdapter adapter) {
        super.setAdapter(adapter == null ? null : new InternalAdapter(adapter));
        if (getAdapterCount() > 0) {
            if (!adapterWasSet) {
                setCurrentItem(getActual(0));
                adapterWasSet = true; 
            }
        }
    }
```

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
