### ISSUE TITLE
API 'variantOutput.getPackageLibrary()' is obsolete

### ISSUE THREAD

**Issue by muzzino** [duolingo/rtl-viewpager#17]
I have updated android studio and there is this message. How can i solve? 

WARNING: API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: rtl-viewpager-master

Thanks

**Comment by DavidDTA** [comment]
Where do you see this message?

**Comment by muzzino** [comment]
see capture image
Thank



![image](https://user-images.githubusercontent.com/5673416/51981127-6469ef00-2492-11e9-886a-2c601e933c22.png)

**Comment by DavidDTA** [comment]
It looks like you've installed this in a non-standard way (i.e. not through Maven).

I've been able to reproduce the problem, though.  I'll update the dependencies and republish.

**Comment by DavidDTA** [comment]
Is this message preventing you from compiling your app?

**Comment by muzzino** [comment]
No the compilation is successful and everything works fine. Thanks a lot for your help.

**Comment by DavidDTA** [comment]
In that case, I'm going to leave the library as is since it's not affecting your workflow, the recommended installation method (through maven) does not have this issue, and the solution is not completely trivial.

If you would like to create a PR yourself, I will help facilitate.

**Comment by muzzino** [comment]
How to do the installation method (through maven)?
I want to solve this problem before it blocks my work.

**Comment by DavidDTA** [comment]
Add the dependencies to the gradle file, as shown [in the readme](https://github.com/duolingo/rtl-viewpager#usage).

**Comment by muzzino** [comment]
thank you so much
