### ISSUE TITLE
how to set navigation drawer appear from RTL with arrow animation

### ISSUE THREAD

**Issue by TaifRaoof** [duolingo/rtl-viewpager#2]
### Required Information

- RtlViewPager Version:
- Android Version and Device (Motorola Droid Razr Maxx with Android 4.4.2, Samsung S7 with Android 6.0, etc...):

### Issue Description
> Please include as many details (logs, steps to reproduce, screenshots) as you can to help us reproduce this issue faster.

**Comment by DavidDTA** [comment]
Hi TaifFaoof,

Please add more description to your issue, particularly sample code.  It is hard to understand your issue without more context.

**Comment by DavidDTA** [comment]
Merging a pull request closed this issue unintentionally.  However, it's old and does not have enough information, so I will leave it closed.
