### ISSUE TITLE
Dynamic adding items is not working

### ISSUE THREAD

**Issue by ValeryBoretsky** [duolingo/rtl-viewpager#24]
Determining position does not work correctly when RTL.
```java
    public void setCurrentItem(int position) {
        PagerAdapter adapter = super.getAdapter();
        if (adapter != null && isRtl()) {
            position = adapter.getCount() - position - 1;
        }
        super.setCurrentItem(position);
    }
```
My case: 
setup position **viewPager.setCurrentItem(i)**. Real position is: **count - i - 1**
add new one item
Try setup position to next item **i + 1**. Real position not changed: **(count + 1) - (i + 1) - 1**

**Comment by DavidDTA** [comment]
I'm not able to determine what the problem is from this description.  Please provide a test case which fails but should pass.

**Comment by ValeryBoretsky** [comment]
```kotlin
@Override
    public void setCurrentItem(int position) {
        Log.d("Test RtlViewPager", "setCurrentItem(" + position + "). getAdapter().getCount() = " + getAdapter().getCount());
        PagerAdapter adapter = super.getAdapter();
        if (adapter != null && isRtl()) {
            position = adapter.getCount() - position - 1;
        }
        Log.d("Test RtlViewPager", "super.setCurrentItem(" + position + ")");
        super.setCurrentItem(position);
    }
```

Test RtlViewPager: setCurrentItem(0). getAdapter().getCount() = 5
Test RtlViewPager: super.setCurrentItem(4)
Test RtlViewPager: setCurrentItem(1). getAdapter().getCount() = 5
Test RtlViewPager: super.setCurrentItem(3)
Test RtlViewPager: setCurrentItem(2). getAdapter().getCount() = 5
Test RtlViewPager: super.setCurrentItem(2)
//add new item to adapter. New count = 6 
Test RtlViewPager: setCurrentItem(3). getAdapter().getCount() = 6
Test RtlViewPager: super.setCurrentItem(2) //oops. Expected 1. Did not happen swipe to next page

**Comment by DavidDTA** [comment]
I need more information about how the item was added.  Nothing in that log output is contradictory yet.  When there are 6 items and `setCurrentItem(3)` is called, `super.setCurrentItem(2)` is expected.

**Comment by ValeryBoretsky** [comment]
```java
int currentItem = mViewPager.getCurrentItem();
if (model.hasErrors()) {
    mPagerAdapter.addModel(newModel);
}
int nextItem = currentItem + 1;
if (nextItem < mPagerAdapter.getCount()) {
    mViewPager.setCurrentItem(nextItem);
} else {
    exit();
}
```

User selects answer on the page. New item added to end when the answer is wrong. Autoscroll to the next page.
After when was added item and enabled RTL autoscroll to the next page does not work

**Comment by DavidDTA** [comment]
Thanks for the further update.  What I am looking for is a Short Self Contained Compilable Example.  See http://sscce.org/ for more information about what that means and why it's important and useful.

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
