### ISSUE TITLE
issue in onMeasure method (Array index out of bounds)

### ISSUE THREAD

**Issue by isandoqa** [duolingo/rtl-viewpager#27]
I am using rtl-viewpager:2.0.0 in my app. I found crashlytics reports with the following details:

devices: 
galaxy tabS 10.5 with android 6.0.1
lenovo k5 note with android 6.0
galaxy note 3 with android 5.0
all in portrait mode.

logs:
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=13; index=-1

at this line
com.duolingo.open.rtlviewpager.RtlViewPager.onMeasure (RtlViewPager.java:231)

here is the full log:
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
length=13; index=-1

com.google.android.flexbox.FlexboxLayoutManager.updateLayoutState (FlexboxLayoutManager.java:2034)
com.google.android.flexbox.FlexboxLayoutManager.handleScrollingCrossAxis (FlexboxLayoutManager.java:1961)
com.google.android.flexbox.FlexboxLayoutManager.fixLayoutStartGap (FlexboxLayoutManager.java:802)
com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren (FlexboxLayoutManager.java:775)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:3924)
androidx.recyclerview.widget.RecyclerView.onMeasure (RecyclerView.java:3336)
android.view.View.measure (View.java:18563)
android.widget.HorizontalScrollView.measureChildWithMargins (HorizontalScrollView.java:1797)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
android.widget.HorizontalScrollView.onMeasure (HorizontalScrollView.java:466)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1435)
android.widget.LinearLayout.measureVertical (LinearLayout.java:721)
android.widget.LinearLayout.onMeasure (LinearLayout.java:612)
android.view.View.measure (View.java:18563)
androidx.core.widget.NestedScrollView.measureChildWithMargins (NestedScrollView.java:1534)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
androidx.core.widget.NestedScrollView.onMeasure (NestedScrollView.java:581)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1435)
android.widget.LinearLayout.measureVertical (LinearLayout.java:721)
android.widget.LinearLayout.onMeasure (LinearLayout.java:612)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
android.view.View.measure (View.java:18563)
androidx.viewpager.widget.ViewPager.onMeasure (ViewPager.java:1638)
com.duolingo.open.rtlviewpager.RtlViewPager.onMeasure (RtlViewPager.java:231)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
androidx.appcompat.widget.LinearLayoutCompat.measureChildBeforeLayout (LinearLayoutCompat.java:1377)
androidx.appcompat.widget.LinearLayoutCompat.measureVertical (LinearLayoutCompat.java:661)
androidx.appcompat.widget.LinearLayoutCompat.onMeasure (LinearLayoutCompat.java:551)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
android.view.View.measure (View.java:18563)
android.widget.RelativeLayout.measureChild (RelativeLayout.java:698)
android.widget.RelativeLayout.onMeasure (RelativeLayout.java:482)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
androidx.appcompat.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java:143)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1435)
android.widget.LinearLayout.measureVertical (LinearLayout.java:721)
android.widget.LinearLayout.onMeasure (LinearLayout.java:612)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1435)
android.widget.LinearLayout.measureVertical (LinearLayout.java:721)
android.widget.LinearLayout.onMeasure (LinearLayout.java:612)
android.view.View.measure (View.java:18563)
android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:5827)
android.widget.FrameLayout.onMeasure (FrameLayout.java:430)
com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure (PhoneWindow.java:2888)
android.view.View.measure (View.java:18563)
android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2250)
android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1306)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1548)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1191)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6644)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:777)
android.view.Choreographer.doCallbacks (Choreographer.java:590)
android.view.Choreographer.doFrame (Choreographer.java:560)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:763)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:5938)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)

**Comment by isandoqa** [comment]
I think it is an issue in android 5 and 6, 
I reproduced it in a simulator (Nexus 4, android 6).
After sliding the pager 5 or 6 times both left and right the app crashes and gives the same error stack trace.

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
