### ISSUE TITLE
Problem after upgrading to the new material library 1.1.0

### ISSUE THREAD

**Issue by alazzam95** [duolingo/rtl-viewpager#28]
### Required Information

- 2.0.0:
- all android versions as far as i know

### Issue Description
i have **com.google.android.material.tabs.TabLayout** which is setup with RTLViewPager with 3 tabs as fragments, and the RTLViewPager adapter is of type FragmentStatePagerAdapter.

The Problem is:
After upgrading to the new material library **com.google.android.material:material:1.1.0**, 
the 3rd tab is not displayed anymore.

I tried to replace RTLViewPager with normal android ViewPager and it worked (the 3rd tab or fragment is displayed normally).
So there is a problem with RTLViewPager when setup with **com.google.android.material.tabs.TabLayout** of the material library version **1.1.0** because it was working fine with material library version **1.0.0**

**Comment by DavidDTA** [comment]
This library is now deprecated and outstanding issues will not be addressed.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
