### ISSUE TITLE
when rotating the screen listeners are notified with the LTR position not RTL

### ISSUE THREAD

**Issue by m7mdyahia** [duolingo/rtl-viewpager#3]
### Required Information

- RtlViewPager Version:
- Android Version and Device (Android 6.0 on Lenovo A-7000 plus):

### Issue Description
when rotating the screen listeners are notified with the LTR position not RTL
by debugging I Found that
ReversingOnPageChangeListener.onPageSelected() is called befor onRestoreInstanceState() is called thus using the default direction which is 0 so the used  

this [condition ](https://github.com/duolingo/rtl-viewpager/blob/master/src/main/java/com/duolingo/open/rtlviewpager/RtlViewPager.java#L244)is bypassed
 if (isRtl() && adapter != null) {
                position = adapter.getCount() - position - 1;
}

you could easily reproduce this by creating a pager and a TextView in the activity showing position

**Comment by m7mdyahia** [comment]
#4

**Comment by DavidDTA** [comment]
Fixed by #4

**Comment by DavidDTA** [comment]
This has been published in version 1.0.2
