### ISSUE TITLE
Change language on runtime

### ISSUE THREAD

**Issue by shayantabatabaee** [duolingo/rtl-viewpager#9]
Hi , thanks for your nice library,
I faced some issue with your library, in my application i'm changing language inside app, so i create a new context and attach it to activity, but after some times to change language the viewpager is not RTL anymore.

thanks.

**Comment by DavidDTA** [comment]
Hi @shayantabatabaee,

I don't have enough information to help you with your request.  The most helpful thing would be a small example app that demonstrates the problem, but has no other functionality ([SSCCE](http://sscce.org/)).

Thanks!
